version: '2.1'

services:
  postgresql:
    image: postgres:9.6
    container_name: postgresql-batchdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "batchdb"
    volumes:
      - ~/docker-volumes/postgresql-batchdb:/var/lib/postgresql/data